name: O Robo Inspetor (DevSecOps)

on:
  push:
    branches: [ "main" ]

jobs:
  inspecionar:
    runs-on: ubuntu-latest

    steps:
      # Passo A: Pega a caixa
      - name: Pega o codigo
        uses: actions/checkout@v4

      # --- INICIO DA ANALISE SAST (BANDIT) ---
      - name: Configurar Python na esteira
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar o inspetor de codigo (Bandit)
        run: pip install bandit

      - name: Inspecionar o codigo Python (SAST)
        run: bandit -r app.py
      # --- FIM DA ANALISE SAST ---

      # --- INICIO DA ANALISE DE INFRAESTRUTURA (TERRAFORM) ---
      - name: Configurar o Terraform na esteira
        uses: hashicorp/setup-terraform@v2

      - name: Inicializar Terraform (Modo Local/Sem Nuvem)
        run: terraform init -backend=false

      - name: Validar a sintaxe e logica do main.tf
        run: terraform validate
      # --- FIM DA ANALISE DE INFRAESTRUTURA ---

      # Passo B: Monta a caixa
      - name: Constroi a caixa do Docker
        run: docker build -t minha-aplicacao:latest .

      # Passo C: O robo inspetor de seguranca entra em acao
      - name: Ligar o Inspetor Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'minha-aplicacao:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'